# page title
page_title: # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id: 1543547997  # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link: # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link: # Enter Google Play Store URL.
presskit_download_link: # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: # assets/appicon.png  # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: |
  Get through your tasks by putting your phone away. To start the timer put your device on the table screen facing down. When the timer finishes you will hear a chime. Enjoy your break and restart when youâ€™re ready again!

enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: Dan Kim
your_link: https://dankim.io
your_city:
email_address:
facebook_username:
instagram_username: dankimio
twitter_username: dankimio
github_username: dankimio
youtube_username:

# Feature List (Edit, add or remove features to be presented.)
features:
  - title: Productivity Timer
    description: Break up your work into intervals. Work on your tasks. Don't forget to take breaks.
    fontawesome_icon_name: hourglass-start

  - title: Put Your Phone Away
    description: Put your phone on the table screen facing down. No distractions.
    fontawesome_icon_name: bell-slash

  - title: Dark Mode, Customization and More
    description: Custom timer length, dark mode and more to come. Stay tuned!
    fontawesome_icon_name: wrench

# Theme Settings
topbar_color: "#fff"
topbar_transparency: 1.0
topbar_title_color: "#000"

cover_image: # Replace with alternative image path or image URL.
cover_overlay_color: "#ffffff"
cover_overlay_transparency: 1.0

device_color: black # Set to: blue, black, yellow, coral or white.

body_background_color: "#F8F8F8"

link_color: "#1d63ea"

app_title_color: "#000"
app_price_color: "#000"
app_description_color: "#000"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#1d63ea"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
